# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:locadoradb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password= Apolo2022$

# Permite que você acesse o painel visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Atualiza a estrutura das tabelas automaticamente com base nos seus Models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true