# Habilita o Console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Força o Hibernate a saber qual Dialect usar caso ele se perca
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true